apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: customers
        image: ronakthakkar/eshopping.customers.service:2.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
